# Site settings
title: Teja Kanchinadam blog
email: 
description: "Uncertainity is the truth"
baseurl: "http://tkanchin.github.io/blog"
url: ""
twitter_username: kanchinadamteja
github_username:  tkanchin

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
