# Site settings
title: Teja Kanchinadam blog
email: 
description: "Uncertainity is the truth"
baseurl: "//tkanchin.github.io/blog"
url: "//tkanchin.github.io/blog"
twitter_username: kanchinadamteja
github_username:  tkanchin

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
